### ISSUE TITLE
Limit the emoji displayed on a project summary to 8

### ISSUE THREAD

**Issue by zspencer** [cohere-coop/capacitor#133]
Long running projects tend to accumulate lots and lots of emoji; when really we only care about the last few months.

**Comment by Wimsy113** [comment]
So  the limit should be 3-4 right?

**Comment by zspencer** [comment]
I'm not sure, I don't remember how we group the emoji; I thought they were
by month, so if we want 2montha then we'd want 8 emojis

On Sunday, January 31, 2016, Krystyna Ewing notifications@github.com
wrote:

> So the limit should be 3-4 right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zincmade/capacitor/issues/133#issuecomment-177599775.

## 

Typed with thubdgjs
