### ISSUE TITLE
Make checking- in more compact

### ISSUE THREAD

**Issue by zspencer** [cohere-coop/capacitor#173]
The way check-ins are now; each activity takes up a ton of space. It'd be nice if  the core data (quality + quantity of attention) and "Do not bill" were all in a row; with a single line of notes underneath?

**Comment by Wimsy113** [comment]
Do you mean the `check_in` on the `new_check_in` page? Or the display under `projects` on the dashboard?

**Comment by zspencer** [comment]
In the new check in page.
