### ISSUE TITLE
User who is on a team may check in to or log against activities from that team

### ISSUE THREAD

**Issue by zspencer** [cohere-coop/capacitor#282]
In order for small groups to work together more effectively,
As a team member
I want to be able to check in or log time against activities for teams I am part of

### Context
Currently, users can only check in or log time against activities that they created, this makes it so when people are on a team, the team doesn't really add anything to their experience.

As we add people working on the same project, it would be nice if all time logged against a project to actually updated the project.

**Comment by jtu0** [comment]
Are "checking in" and "logging time" different actions, or different names for the same action @zspencer

**Comment by zspencer** [comment]
Checking in is filling out an entire days worth of activity at a time. You can add a single log entry by going to the logs page and adding a new entry.

In the end, we need a source of truth for "Which Activities I can log time against?" which probably deserves to live on the Account object for now; and then we need to update wherever we use `account.activities` in the views or controllers to use the new collection.
